// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shatter.Core.Database;

namespace Shatter.Core.Migrations
{
    [DbContext(typeof(ShatterDatabaseContext))]
    [Migration("20201127211835_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Shatter.Core.Structures.Guilds.GuildConfig", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivatedCommands")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowPublicTriviaGames")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisabledCommands")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisabledModules")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TriviaQuestionLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("Configs");
                });

            modelBuilder.Entity("Shatter.Core.Structures.Guilds.GuildFilters", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BypassFilters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Filters")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("Filters");
                });

            modelBuilder.Entity("Shatter.Core.Structures.Guilds.GuildMemberlogs", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("JoinDmMessage")
                        .HasColumnType("TEXT");

                    b.Property<ulong?>("MemberlogChannel")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("Memberlogs");
                });

            modelBuilder.Entity("Shatter.Core.Structures.Guilds.GuildModeration", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("ModLogChannel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SlowmodeLocks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserBans")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserMutes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("Moderations");
                });

            modelBuilder.Entity("Shatter.Core.Structures.Trivia.TriviaPlayer", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsIncorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("TriviaPlayers");
                });

            modelBuilder.Entity("Shatter.Core.Structures.Wallet", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastDaily")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Shatter.Core.Structures.Guilds.GuildMemberlogs", b =>
                {
                    b.OwnsOne("Shatter.Core.Structures.MemberlogMessage", "JoinMessage", b1 =>
                        {
                            b1.Property<ulong>("GuildMemberlogsGuildId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsEmbed")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsImage")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Message")
                                .HasColumnType("TEXT");

                            b1.HasKey("GuildMemberlogsGuildId");

                            b1.ToTable("Memberlogs");

                            b1.WithOwner()
                                .HasForeignKey("GuildMemberlogsGuildId");
                        });

                    b.OwnsOne("Shatter.Core.Structures.MemberlogMessage", "LeaveMessage", b1 =>
                        {
                            b1.Property<ulong>("GuildMemberlogsGuildId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("IsEmbed")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsImage")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Message")
                                .HasColumnType("TEXT");

                            b1.HasKey("GuildMemberlogsGuildId");

                            b1.ToTable("Memberlogs");

                            b1.WithOwner()
                                .HasForeignKey("GuildMemberlogsGuildId");
                        });

                    b.Navigation("JoinMessage");

                    b.Navigation("LeaveMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
