# This is a basic workflow that is manually triggered

name: Release Artifact to Live

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download Latest Release
        uses: actions/download-artifact@v2.0.6
        with:
          name: "s-release"
          path: artifact/
      - name: Stop Current Release
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{ secrets.DOCKER_STOP_CMD }}
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
          privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
      - name: Copy Files over SSH
        uses: garygrossgarten/github-action-scp@release
        with:
          local: artifact/
      - name: Start New Release
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{ secrets.START_DOCKER_CMD }}
          host: ${{ secrets.RELEASE_HOST }}
          username: ${{ secrets.RELEASE_USER }}
          passphrase: ${{ secrets.RELEASE_PASSPHRASE }}
          privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
